#include"stm32f4xx.h"
int main(void){
SET_BIT(RCC->AHBENR,RCC_AHB1ENR_GPIOACEN);
SET_BIT(RCC->AHBENR,RCC_AHB1ENR_GPIOCCEN);

GPIOC->MODER &= ~(GPIOC_MODER_MODER13);
GPIOC->MODER |= (GPIOC_MODER_MODER13_0);

GPIOA->MODER &= ~(GPIOC_MODER_MODER13);

//PP

GPIOC->PUPDR &= ~(GPIOC_PUPDR_PUPDR0);
GPIOC->PUPDR |= (GPIOC_PUPDR_PUPDR0);

while(1){
((GPIOA->IDRA &= (GPIOA_IDR_IDR0)==GPIOA_IDR_IDR0)
{
 GPIOC->BSSR |= GPIO_BSSR_BR13;
}
else
{
GPIOC->BSSR |= GPIO_BSSR_BS13;
}
}
}
